Repository FRONTENDSCHOOL7/villains, pull requests merged in 2023-11, with the labels that each got.

#69 [ADD] 글로벌 스타일 추가
  src/components/Buttons.jsx
  src/components/GlobalButton.jsx
  src/components/PageTemplate.jsx
  src/components/layout/Header.jsx
  src/components/searchbar/SearchBar.jsx
  src/style/theme.js
  src/views/Result.view.jsx
Labels: FEAT

#70 [ADD] 지하철 요일 및 방향 선택 시간표 조회 기능 추가
  src/components/Buttons.jsx
  src/components/GlobalButton.jsx
  src/views/Result.view.jsx
Labels: FEAT

#71 [ADD] 댓글 작성, 불러오기 UI 추가
  package-lock.json
  package.json
  src/api/postComments.api.js
  src/assets/fonts/SUIT-ExtraLight.woff2
  src/assets/fonts/SUIT-Heavy.woff2
  src/assets/fonts/SUIT-Light.woff2
  src/assets/fonts/SUIT-SemiBold.woff2
  src/assets/fonts/SUIT-Thin.woff2
  src/assets/fonts/SUIT.css
  src/assets/img/icon-more-vertical.svg
  src/components/PageTemplate.jsx
  src/components/feed/Comment.jsx
  src/components/feed/ResizingTextarea.jsx
  src/config/pageUrlConfig.js
  src/config/route.config.jsx
  src/hooks/useFormatDate.js
  src/views/FeedDetail.view.jsx
  src/views/FeedWrite.view.jsx
Labels: FEAT

#72 [STYLE] 페이지 레이아웃 스타일 수정
  public/img/write.svg
  public/nav/nav-chat-click.svg
  public/nav/nav-chat.svg
  public/nav/nav-feed-click.svg
  public/nav/nav-feed.svg
  public/nav/nav-goods-click.svg
  public/nav/nav-goods.svg
  public/nav/nav-main-click.svg
  public/nav/nav-main.svg
  public/nav/nav-user-click.svg
  public/nav/nav-user.svg
  src/components/Buttons.jsx
  src/components/FloatingButton.style.jsx
  src/components/PageTemplate.jsx
  src/components/feed/Feed.jsx
  src/components/layout/Header.jsx
  src/components/layout/NavMenu.jsx
  src/views/Feed.view.jsx
  src/views/Home.view.jsx
Labels: FEAT

#75 [ADD] 택배 목록 페이지 구현
  src/api/getProducts.api.js
  src/components/CheckBox.jsx
  src/components/Goods.jsx
  src/components/SearchSub.jsx
  src/views/Goods.view.jsx
  src/views/GoodsWrite.view.jsx
  src/views/SignIn.view.jsx
  src/views/SignUp.view.jsx
Labels: FEAT

#77 [ADD] 댓글 삭제, 신고 기능 추가
  src/api/deleteComments.api.js
  src/api/getComments.api.js
  src/api/getPostDetail.api.js
  src/api/getPosts.api.js
  src/api/postComments.api.js
  src/api/postCommentsReport.api.js
  src/api/postHeart.api.js
  src/atoms/bottomSheetStateAtom.js
  src/components/BottomSheet.jsx
  src/components/FloatingButton.style.jsx
  src/components/PageTemplate.jsx
  src/components/feed/Comment.jsx
  src/components/feed/CommentForm.jsx
  src/components/feed/Feed.jsx
  src/components/feed/PostCard.jsx
  src/components/layout/BackHeader.jsx
  src/components/layout/Header.jsx
  src/config/route.config.jsx
  src/hooks/useBlockToBack.js
  src/views/FeedDetail.view.jsx
  src/views/FeedWrite.view.jsx
Labels: FEAT

#83 [ADD] 택배 상세 페이지 추가
  src/api/getProductDetail.api.js
  src/api/getUserDetail.api.js
  src/components/Goods.jsx
  src/config/pageUrlConfig.js
  src/config/route.config.jsx
  src/views/GoodsDetail.view.jsx
Labels: FEAT

#84 [ADD] 유저 페이지 관련 API 추가
  src/api/deleteFollow.js
  src/api/getFollowingList.js
  src/api/getMyInfo.js
  src/api/getSearchUser.js
  src/api/getUserInfo.js
  src/api/getUserPost.api.js
  src/api/postFollow.js
  src/api/updateUser.js
  src/config/route.config.jsx
  src/views/Home.view.jsx
  src/views/Result.view.jsx
Labels: FEAT

#85 [CORS] 빌드 관련 옵션 수정 및 api 키 적용
  index.html
  jsconfig.json
  vite.config.js
Labels: CORS

#87 [FIX] APP.jsx의 훅 콜 수정
  src/App.jsx
  vite.config.js
Labels: BUG

#88 [FIX] APP.jsx에서 나오는 에러 수정
  src/App.jsx
  vite.config.js
Labels: BUG

#89 [UPDATE] 환경변수 적용 수정
  .github/workflows/deploy.yml
Labels: BUG

#90 [CORS] 배포 관련 설정 수정
  .github/workflows/deploy.yml
  src/App.jsx
  vite.config.js
Labels: BUG, CORS

#91 [CORS] base url 설정 변경
  src/config/route.config.jsx
  vite.config.js
Labels: CORS

#92 [FIX] child route path 시작 부분 변경
  src/config/route.config.jsx
Labels: BUG

#93 [FIX] ROUTE에 BASEURL 적용하기
  src/config/route.config.jsx
Labels: BUG

#95 [FIX] BASE URL 4차 수정
  vite.config.js
Labels: BUG

#96 [FIX] base url 설정
  src/config/route.config.jsx
  vite.config.js
Labels: BUG

#97 [MODIFY] 페이지 라우트 수정
  src/config/pageUrlConfig.js
  src/config/route.config.jsx
Labels: BUG, CORS

#98 [MODIFY] 스플래시 url 변경
  src/config/pageUrlConfig.js
  src/config/route.config.jsx
Labels: CORS

#100 [ADD] 게시글 수정, 삭제, 신고 기능 추가
  src/api/deletePost.api.js
  src/api/postImages.api.js
  src/api/postReport.api.js
  src/api/putPostEdit.api.js
  src/api/uploadPost.api.js
  src/assets/img/write.svg
  src/components/BottomSheet.jsx
  src/components/FloatingButton.style.jsx
  src/components/feed/Comment.jsx
  src/components/feed/Feed.jsx
  src/config/pageUrlConfig.js
  src/config/route.config.jsx
  src/hooks/useBottomSheetOptions.js
  src/views/Feed.view.jsx
  src/views/FeedDetail.view.jsx
  src/views/FeedWrite.view.jsx
Labels: FEAT

#104 [ADD] 택배 상세 페이지 + 택배 수정 페이지
  src/api/deleteProduct.api.js
  src/api/getProducts.api.js
  src/api/updateProduct.api.js
  src/atoms/realProductAuthorAtom.js
  src/components/DropDown.jsx
  src/components/Goods.jsx
  src/components/SearchSub.jsx
  src/components/Tanghulu.jsx
  src/components/layout/PrivateLayout.jsx
  src/config/pageUrlConfig.js
  src/config/route.config.jsx
  src/views/Goods.view.jsx
  src/views/GoodsDetail.view.jsx
  src/views/GoodsWrite.view.jsx
Labels: FEAT

#105 [ADD] 유저 검색 기능 추가
  src/api/getSearchUser.js
  src/components/layout/BackHeader.jsx
  src/components/layout/SearchLayout.jsx
  src/components/searchbar/UserCard.jsx
  src/components/searchbar/UserListBox.jsx
  src/views/FeedDetail.view.jsx
  src/views/FeedWrite.view.jsx
Labels: FEAT

#110 [FIX] 없어진 코드 추가
  src/components/Goods.jsx
  src/components/layout/PrivateLayout.jsx
  src/views/auth/SignIn.view.jsx
  src/views/auth/SignUp.view.jsx
  src/views/auth/Splash.view.jsx
  src/views/goods/Goods.view.jsx
  src/views/goods/GoodsDetail.view.jsx
  src/views/goods/GoodsWrite.view.jsx
Labels: FEAT

#113 [ADD] 지하철역 표시 기능 추가
  jsconfig.json
  src/api/delete/deleteProduct.api.js
  src/api/get/getUserPost.api.js
  src/api/loader/searchPlace.loader.js
  src/api/update/updateProduct.api.js
  src/atoms/stationPlaceAtom.js
  src/atoms/userPostAtom.js
  src/components/layout/BackHeader.jsx
  src/components/layout/PrivateLayout.jsx
  src/components/layout/SearchHeader.jsx
  src/components/map/TrainMap.jsx
  src/components/searchbar/ListBox.jsx
  src/config/route.config.jsx
  src/hooks/useGeoLocation.js
  src/hooks/useSearchData.js
  src/views/goods/GoodsDetail.view.jsx
  src/views/goods/GoodsWrite.view.jsx
  src/views/home/Home.view.jsx
  src/views/home/Result.view.jsx
  src/views/home/Train.view.jsx
  src/views/home/index.view.jsx
Labels: FEAT

#116 [ADD] 택배 페이지 헤더 + 팔로워,팔로잉 페이지
  src/api/get/getFollowingList.api.js
  src/api/get/getUserFollower.api.js
  src/api/post/postFollow.api.js
  src/api/post/postUnFollow.api.js
  src/atoms/followPageStateAtom.js
  src/atoms/headerBtnStateAtom.js
  src/components/Buttons.jsx
  src/components/Follower.jsx
  src/views/auth/SignUp.view.jsx
  src/views/goods/GoodsWrite.view.jsx
  src/views/goods/index.view.jsx
  src/views/user/ProfileFollow.view.jsx
Labels: FEAT

#117 [ADD] 공통 모달 컴포넌트, 에러 페이지 추가
  src/api/get/getSearchUser.api.js
  src/assets/img/icon-404.svg
  src/components/Modal.jsx
  src/components/PageTemplate.jsx
  src/components/PageTemplate.style.js
  src/components/feed/Comment.jsx
  src/components/feed/PostCard.jsx
  src/components/layout/NavMenu.jsx
  src/components/layout/SearchLayout.jsx
  src/components/searchbar/UserListBox.jsx
  src/hooks/useModal.js
  src/views/Error.jsx
  src/views/Error.view.jsx
  src/views/chat/Chat.view.jsx
  src/views/chat/index.view.jsx
  src/views/feed/Feed.view.jsx
  src/views/feed/FeedDetail.view.jsx
  src/views/feed/FeedWrite.view.jsx
  src/views/feed/index.view.jsx
Labels: FEAT

#119 [UPDATE] 지하철역 지도에 표시하는 기능 업데이트
  src/api/get/getUserInfo.api.js
  src/api/get/getUserPost.api.js
  src/api/loader/searchPlace.loader.js
  src/atoms/profileAtom.js
  src/components/PageTemplate.jsx
  src/components/PageTemplate.style.js
  src/components/layout/BackHeader.jsx
  src/components/layout/PrivateLayout.jsx
  src/components/map/TrainMap.jsx
  src/views/auth/SignIn.view.jsx
  src/views/goods/GoodsDetail.view.jsx
  src/views/home/Home.view.jsx
  src/views/home/Result.view.jsx
  src/views/home/Train.view.jsx
  src/views/home/index.view.jsx
Labels: FEAT, BUG

#120 [ADD] 채팅 페이지 UI 구현
  src/components/PageTemplate.style.js
  src/components/chat/ChatInputField.jsx
  src/components/chat/ChatListItem.jsx
  src/components/chat/Message.jsx
  src/components/feed/Comment.jsx
  src/components/layout/NavMenu.jsx
  src/components/layout/PrivateLayout.jsx
  src/config/pageUrlConfig.js
  src/config/route.config.jsx
  src/hooks/useModal.js
  src/views/chat/Chat.view.jsx
  src/views/chat/ChatDetail.view.jsx
  src/views/chat/index.view.jsx
  src/views/feed/FeedWrite.view.jsx
  src/views/feed/index.view.jsx
Labels: FEAT

#121 [STYLE] 페이지 레이아웃 일부 스타일 수정
  src/components/PageTemplate.style.js
  src/components/layout/NavMenu.jsx
Labels: FEAT

#123 [ADD] 채팅 페이지 기능 구현
  src/api/get/getChatPost.api.js
  src/components/DropDown.jsx
  src/components/chat/ChatInputField.jsx
  src/components/chat/ChatListItem.jsx
  src/components/chat/Message.jsx
  src/config/pageUrlConfig.js
  src/views/auth/SignIn.view.jsx
  src/views/chat/Chat.view.jsx
  src/views/chat/ChatDetail.view.jsx
  src/views/chat/index.view.jsx
  src/views/goods/GoodsDetail.view.jsx
Labels: FEAT

#125 [ADD] 로딩 스켈레톤, 스피너 UI 추가
  package-lock.json
  package.json
  public/img/Logo.png
  public/img/Logo1.svg
  public/img/Logo2.svg
  src/api/get/getPosts.api.js
  src/components/LoadingSpinner.jsx
  src/components/SkeletonCard.jsx
  src/components/SkeletonList.jsx
  src/views/auth/Splash.view.jsx
  src/views/feed/Feed.view.jsx
  src/views/feed/FeedWrite.view.jsx
  src/views/goods/Goods.view.jsx
Labels: FEAT

#126 [ADD] 프로필 페이지 및 수정 기능 추가
  src/App.jsx
  src/api/delete/deleteFollow.api.js
  src/api/loader/sendUserInfo.loader.js
  src/api/post/postFollow.api.js
  src/api/post/postUnFollow.api.js
  src/api/update/updateUser.api.js
  src/atoms/tirggerAtom.js
  src/components/Follower.jsx
  src/components/SearchSub.jsx
  src/components/default/BottomSheet.jsx
  src/components/default/Buttons.jsx
  src/components/default/CheckBox.jsx
  src/components/default/DropDown.jsx
  src/components/default/FloatingButton.style.jsx
  src/components/default/GlobalButton.jsx
  src/components/default/Input.style.jsx
  src/components/default/Tanghulu.jsx
  src/components/feed/PostCard.jsx
  src/components/layout/BackHeader.jsx
  src/components/layout/DefautlLayout.jsx
  src/components/layout/NavMenu.jsx
  src/components/layout/PageTemplate.jsx
  src/components/layout/PageTemplate.style.js
  src/components/layout/PrivateLayout.jsx
  src/components/map/TrainMap.jsx
  src/config/route.config.jsx
  src/views/FollowersList.view.jsx
  src/views/FollowingsList.view.jsx
  src/views/auth/SignIn.view.jsx
  src/views/auth/SignUp.view.jsx
  src/views/auth/Splash.view.jsx
  src/views/chat/Chat.view.jsx
  src/views/chat/ChatDetail.view.jsx
  src/views/chat/index.view.jsx
  src/views/feed/Feed.view.jsx
  src/views/feed/FeedDetail.view.jsx
  src/views/feed/FeedWrite.view.jsx
  src/views/feed/index.view.jsx
  src/views/goods/Goods.view.jsx
  src/views/goods/GoodsDetail.view.jsx
  src/views/goods/GoodsWrite.view.jsx
  src/views/goods/index.view.jsx
  src/views/home/Home.view.jsx
  src/views/home/Result.view.jsx
  src/views/home/Train.view.jsx
  src/views/user/Profile.view.jsx
  src/views/user/ProfileEdit.view.jsx
  src/views/user/ProfileFollow.view.jsx
  src/views/user/index.view.jsx
Labels: FEAT

#127 [FIX] 지하철역 표시 기능 수정
  src/components/map/TrainMap.jsx
Labels: BUG

#129 [ADD] 로그아웃 기능 구현
  index.html
  package.json
  src/App.jsx
  src/api/delete/deleteFollow.api.js
  src/components/default/BottomSheet.jsx
  src/components/default/Tanghulu.jsx
  src/components/layout/PageTemplate.style.js
  src/components/splash/logout.js
  src/hooks/useBottomSheetOptions.js
  src/views/home/Home.view.jsx
  src/views/user/index.view.jsx
Labels: FEAT

#131 [CORS] 라우터 재설정
  jsconfig.json
  src/config/route.config.jsx
  vite.config.js
Labels: BUG, CORS

#132 [FIX] 라우터 자체 lazy 사용
  src/config/route.config.jsx
Labels: CORS

#133 [FIX] lazy 로딩 안되는 부분 수정
  jsconfig.json
  package-lock.json
  package.json
  src/api/loader/searchPlace.loader.js
  src/components/map/TrainMap.jsx
  src/config/route.config.jsx
  src/views/home/Train.view.jsx
  vite.config.js
Labels: BUG

#137 [FIX] 프로필 페이지 수정
  src/api/get/getProducts.api.js
  src/views/auth/SignIn.view.jsx
  src/views/goods/GoodsDetail.view.jsx
  src/views/user/Profile.view.jsx
  src/views/user/ProfileEdit.view.jsx
Labels: FEAT

#138 [FIX] 프로필 페이지 수정 #137
  src/api/get/getProducts.api.js
  src/views/auth/SignIn.view.jsx
  src/views/goods/GoodsDetail.view.jsx
  src/views/user/Profile.view.jsx
  src/views/user/ProfileEdit.view.jsx
Labels: FEAT

#139 [FIX] 팔로워,팔로잉 페이지 수정 #17
  src/views/user/ProfileFollow.view.jsx
Labels: FEAT

#140 [FIX] 팔로워, 팔로잉 페이지 수정
  src/views/user/ProfileFollow.view.jsx
Labels: FEAT

#141 [FIX] 기능 오류들 수정
  src/api/get/getProducts.api.js
  src/components/layout/NavMenu.jsx
  src/components/searchbar/UserCard.jsx
  src/config/route.config.jsx
  src/views/chat/index.view.jsx
  src/views/feed/Feed.view.jsx
  src/views/feed/index.view.jsx
  src/views/goods/index.view.jsx
  src/views/user/Profile.view.jsx
  src/views/user/ProfileEdit.view.jsx
  src/views/user/index.view.jsx
Labels: FEAT, BUG

#142 [FIX] 기능 오류들 수정
  src/api/get/getProducts.api.js
  src/components/layout/NavMenu.jsx
  src/components/searchbar/UserCard.jsx
  src/config/route.config.jsx
  src/views/chat/index.view.jsx
  src/views/feed/Feed.view.jsx
  src/views/feed/index.view.jsx
  src/views/goods/index.view.jsx
  src/views/user/Profile.view.jsx
  src/views/user/ProfileEdit.view.jsx
  src/views/user/index.view.jsx
Labels: FEAT, BUG

#144 [STYLE] 택배 상태 색상 변경 #63
  src/views/goods/GoodsDetail.view.jsx
Labels: FEAT

#145 [STYLE] 택배 상태 색상 변경 #63
  src/views/goods/GoodsDetail.view.jsx
Labels: FEAT

#146 [ADD] 리드미 추가
  README.md
Labels: DOCS

#148 [FIX] 로그아웃 후 이동 경로 수정
  README.md
  src/views/user/Profile.view.jsx
  src/views/user/index.view.jsx
Labels: BUG

#149 [ADD] 아이콘 교체 및 오픈 API - mixed contents 허용
  index.html
  src/components/profile/ShareIcon.jsx
  src/views/user/Profile.view.jsx
Labels: FEAT, BUG
