Repository FRONTENDSCHOOL7/villains, pull requests merged in 2023-10, with the labels that each got.

#11 [ADD] PR 템플릿 추가
  .github/pull_request_template.md
  README.md
  package-lock.json
  package.json
Labels: FEAT

#26 [ADD] 지도 페이지 기능 추가
  index.html
  package-lock.json
  package.json
  src/App.jsx
  src/api/getUserPost.js
  src/components/searchbar/SearchBar.jsx
  src/config/api.config.js
  src/config/contact.jsx
  src/config/route.config.jsx
  src/hooks/useGeoLocation.jsx
  src/index.jsx
  src/views/Home.view.jsx
Labels: FEAT

#33 [FIX] API에 헤더가 잘못 들어가는 경우 수정
  src/api/getUserPost.js
  src/config/api.config.js
  src/views/Home.view.jsx
Labels: BUG

#34 [ADD] 로그인, 회원가입 페이지 추가
  package-lock.json
  package.json
  src/assets/fonts/SUIT-Bold.woff2
  src/assets/fonts/SUIT-ExtraBold.woff2
  src/assets/fonts/SUIT-ExtraLight.woff2
  src/assets/fonts/SUIT-Heavy.woff2
  src/assets/fonts/SUIT-Light.woff2
  src/assets/fonts/SUIT-Medium.woff2
  src/assets/fonts/SUIT-Regular.woff2
  src/assets/fonts/SUIT-SemiBold.woff2
  src/assets/fonts/SUIT-Thin.woff2
  src/assets/fonts/SUIT.css
  src/assets/img/email.svg
  src/assets/img/facebook.svg
  src/assets/img/google.svg
  src/assets/img/kakao.svg
  src/components/Buttons.jsx
  src/components/PageTemplate.jsx
  src/components/SmallBtn.jsx
  src/components/SnsBtn.jsx
  src/config/pageUrlConfig.js
  src/config/route.config.jsx
  src/index.jsx
  src/style/GlobalStyles.jsx
  src/views/SignIn.view.jsx
  src/views/SignUp.view.jsx
  src/views/Splash.view.jsx
Labels: FEAT

#39 [FIX] Button 컴포넌트 수정 + 로그인 오류 수정 + CheckBox 컴포넌트 추가 + 뒤로가기 막기 구현
  src/components/Buttons.jsx
  src/components/CheckBox.jsx
  src/views/SignIn.view.jsx
  src/views/SignUp.view.jsx
  src/views/Splash.view.jsx
Labels: FEAT

#43 [MODIFY] 작업 머지 과정에서 디테일한 부분 수정
  package-lock.json
  src/components/PageTemplate.jsx
  src/components/layout/Header.jsx
  src/config/route.config.jsx
  src/views/Home.view.jsx
  src/views/feed/Feed.view.jsx
  src/views/feed/FeedDetail.view.jsx
  src/views/feed/FeedWrite.view.jsx
  src/views/sign/SignIn.view.jsx
  src/views/sign/SignUp.view.jsx
  src/views/sign/Splash.view.jsx
Labels: FEAT

#44 Revert "[MODIFY] 작업 머지 과정에서 디테일한 부분 수정"
  package-lock.json
  src/components/PageTemplate.jsx
  src/components/layout/Header.jsx
  src/config/route.config.jsx
  src/views/Feed.view.jsx
  src/views/FeedDetail.view.jsx
  src/views/FeedWrite.view.jsx
  src/views/Home.view.jsx
  src/views/SignIn.view.jsx
  src/views/SignUp.view.jsx
  src/views/Splash.view.jsx
Labels: HELP

#45 [FIX] 변경 파일 복구
  src/views/Splash.view.jsx
Labels: HELP

#51 [ADD] 환경변수 배포용 모드 추가
  .github/workflows/page.yml
  .gitignore
  src/components/layout/Header.jsx
  vite.config.js
Labels: BUG

#52 [MODIFY] 파일 경로 수정
  src/components/layout/Header.jsx
Labels: BUG

#53 [MODIFY] 배포용 base URL 수정
  vite.config.js
Labels: BUG

#62 [ADD] 지하철역 시간표 검색 기능 추가
  index.html
  src/api/getSubOneInfo.js
  src/api/getSubTime.api.js
  src/components/Buttons.jsx
  src/components/PageTemplate.jsx
  src/components/layout/Header.jsx
  src/components/searchbar/ListBox.jsx
  src/components/searchbar/SearchBar.jsx
  src/config/pageUrlConfig.js
  src/config/route.config.jsx
  src/database/2023-2024-holiday.json
  src/views/Home.view.jsx
  src/views/Result.view.jsx
Labels: FEAT

#64 [ADD] 댓글 불러오기, 댓글 작성 기능 추가
  src/api/getComments.api.js
  src/api/getPostDetail.api.js
  src/api/postComments.api.js
  src/api/uploadPost.api.js
  src/components/Buttons.jsx
  src/components/feed/Comment.jsx
  src/components/feed/Feed.jsx
  src/components/feed/FeedDetail.jsx
  src/components/feed/IconActionButton.jsx
  src/components/feed/PostCard.jsx
  src/config/pageUrlConfig.js
  src/config/route.config.jsx
  src/style/swiperStyle.js
  src/views/FeedDetail.view.jsx
  src/views/FeedWrite.view.jsx
Labels: FEAT

#65 [ADD] 택배 등록 페이지 추가
  src/api/postImage.js
  src/assets/img/active-chat.svg
  src/assets/img/active-feed.svg
  src/assets/img/active-goods.svg
  src/assets/img/active-home.svg
  src/assets/img/active-user.svg
  src/assets/img/chat.svg
  src/assets/img/feed.svg
  src/assets/img/goods.svg
  src/assets/img/home.svg
  src/assets/img/icon-search.svg
  src/assets/img/user.svg
  src/atoms/goodsFocusEndAtom.js
  src/atoms/goodsFocusStartAtom.js
  src/atoms/goodsQueryEndAtom.js
  src/atoms/goodsQueryStartAtom.js
  src/components/Buttons.jsx
  src/components/DropDown.jsx
  src/components/Input.style.jsx
  src/components/SearchSub.jsx
  src/config/pageUrlConfig.js
  src/config/route.config.jsx
  src/views/GoodsWrite.view.jsx
  src/views/SignIn.view.jsx
Labels: FEAT

#66 [ADD] 프로필 페이지
  package-lock.json
  src/App.jsx
  src/assets/img/menu-list.svg
  src/assets/img/user-icon.svg
  src/components/Buttons.jsx
  src/components/PageTemplate.jsx
  src/components/layout/Header.jsx
  src/components/layout/NavMenu.jsx
  src/components/splash/Splash.style.js
  src/config/pageUrlConfig.js
  src/config/route.config.jsx
  src/index.jsx
  src/views/Chat.view.jsx
  src/views/CheckBox.jsx
  src/views/Feed.view.jsx
  src/views/Goods.view.jsx
  src/views/Home.view.jsx
  src/views/Profile.view.jsx
  src/views/ProfileEdit.view.jsx
  src/views/SignIn.view.jsx
  src/views/SignUp.view.jsx
Labels: FEAT
